language: go
go_import_path: sigs.k8s.io/aws-iam-authenticator
go:
  - 1.13.x

sudo: required

services:
  - docker

install:
  - curl -s -L --retry 8 -o /tmp/goreleaser.tgz https://github.com/goreleaser/goreleaser/releases/download/v0.115.0/goreleaser_Linux_x86_64.tar.gz
  - tar -xzvf /tmp/goreleaser.tgz -C /tmp/
  - sudo mv /tmp/goreleaser /usr/local/bin

script:
  - hack/check-vendor.sh
  - make build test
